### ISSUE TITLE
安装后提示Not Supported

### ISSUE THREAD

**Issue by ShmilyStar** [leeyuentuen/localtuya#25]
Not Supported
Options cannot be edited when configured via YAML.

YAML 配置文件写的是
localtuya:
  - host: 192.168.2.157
    device_id: 6c75d83dc27e62b184mvil
    local_key: d27932c1ee0ee13e
    friendly_name: Tuya Gateway
    protocol_version: "3.3"
    is_gateway: true

**Comment by leeyuentuen** [comment]
this is normally normal, a device that has been configured in YAML, can't be changed in the config flow
