### ISSUE TITLE
It prompts to add entity even if _Is gateway_ is ticked

### ISSUE THREAD

**Issue by felipecrs** [leeyuentuen/localtuya#31]
I think it was not supposed to do that. Was it?

https://user-images.githubusercontent.com/29582865/212754433-2cae7166-3e24-4d1a-ae30-570477a90bf9.mp4

**Comment by nhailong** [comment]
Having the same issue here

**Comment by alexualbu** [comment]
@felipecrs , @nhailong which version are you on?

**Comment by felipecrs** [comment]
v3.6.4

**Comment by alexualbu** [comment]
The simplest cause for this I can think of is that the device is either not a gateway or it somehow has DPs - the code now assumes that a gateway does not have DPs so if it finds any the "is gateway" checkbox is basically disregarded. You could eliminate this hypothesis by either going to the next step in the flow and seeing if any DPs are available or in the Tuya Cloud console by checking [Device Specification](https://eu.iot.tuya.com/cloud/explorer?id=p1633006240965tnmxfh&groupId=group-controll&interfaceId=1468907137894715400)

**Comment by alexualbu** [comment]
That's interesting. I assume it makes sense that some gateways would also expose some functions - it seems that this gateway is alarm related. I guess in this case the logic is in order and it should be ok for you to add a entity just to be able to set it up.

**Comment by felipecrs** [comment]
Hm... that makes sense, but what if I don't want to add any entity? I think it would be helpful to have an option like _Do not prompt for adding entities_ in this case.

**Comment by alexualbu** [comment]
In general I believe this is the paradigm for LocalTuya in general - I am not sure you can add a non-gateway device without adding any of its entities. So although I see your point, this approach would also make sense in this case.

**Comment by alexualbu** [comment]
Hi, @felipecrs !
I added the second gateway I had not used and, concidence, it's the same as yours. So I found an easy way to add an option in the config flow for this.
Opened a PR which is referenced above.

**Comment by alexualbu** [comment]
@felipecrs, can you test the latest release (3.6.6) and confirm it's ok?

**Comment by AlirezaT** [comment]
I have a Bluetooth gateway which is a socket with relay and power measurement. [ALUSSO Gateway](https://www.alussolighting.store/en-be/collections/smart-ligtings/products/wifi-smart-plug-eu-standard-with-tuya-bluetooth-gateway-function)

- It could be configured as a normal switch and works fine
- As a gateway to control BL-Light:
  The first time trying to toggle the light, the gateway relay gets toggled and then the light is under control properly.
is there a way to define DP for such a gateway and still use it as Gateway?

that might also fix this conflict.

I've tried to `is_gateway: false` in configuration.yaml but the BL light becomes unavailable by doing this!

I need to have `is_gateway: true` & define entities for the Hub at the same time
