### ISSUE TITLE
Tuya zigbee motion sensor unavailable

### ISSUE THREAD

**Issue by robertrebor** [leeyuentuen/localtuya#62]
Dear all

i tried to use this integration for my ZIgbee motion sensor. 
I tried to use YAML and UI configuration, but I have only unavailable status for DPs. 

Is anybody here who has some zigbee device and these devices run correctly? I can't find solution how to solve my problem.
<img width="241" alt="image" src="https://user-images.githubusercontent.com/114231763/235885671-bd0cab7f-ea46-4ba4-8d75-59b233d06343.png">

  # MY CODE

localtuya:
  - host: 192.168.3.18
    device_id: bf30fe97XXXXXXX
    local_key: 78ffaXXXXXX
    friendly_name: Gateway_new
    protocol_version: "3.4"
    is_gateway: true 

  - parent_gateway: Gateway_new 
    device_id: bf7bc61XXXXX
    friendly_name: Tuya Zigbee PIR Sensor
    entities:
      - platform: binary_sensor
        friendly_name: Motion Sensor
        id: 1
        device_class: motion
        state_on: pir
        state_off: none
      - platform: sensor
        friendly_name: Sensor Battery
        id: 4
        device_class: battery

# TUYA IOT
{
  "result": {
    "category": "pir",
    "functions": [],
    "status": [
      {
        "code": "pir",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"pir\",\"none\"]}"
      },
      {
        "code": "battery_percentage",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1683102440269,
  "tid": "52377119e98c11ed8b506a01366d7453"
}

**Comment by alexualbu** [comment]
@robertrebor, please enable debug logs and provide the full logs. I have similar PIRs judging by the DP list and they work fine.

**Comment by robertrebor** [comment]
> @robertrebor, please enable debug logs and provide the full logs. I have similar PIRs judging by the DP list and they work fine.

@alexualbu can you write me short manual how I can enable debug logs? I am not familiar with debugging :(

**Comment by robertrebor** [comment]
@alexualbu I tried to add logger and I got file in attachment

[home-assistant_localtuya_2023-05-15T19-43-46.311Z.log](https://github.com/leeyuentuen/localtuya/files/11481497/home-assistant_localtuya_2023-05-15T19-43-46.311Z.log)

**Comment by alexualbu** [comment]
@robertrebor , my suspicion right now is that you are using the montion sensor device_id instead of the cid / node_id. Can you confirm? You can grab the node_id from the tuya developer console, api explorer, get Device Specification
![image](https://github.com/leeyuentuen/localtuya/assets/48317290/a017f2d0-649c-4ac8-8829-93481e6be745)

**Comment by robertrebor** [comment]
@alexualbu you are absolutely right. I am stupid, I used device_id. Now is everything absolutely OK. Thank you very much. 

Issue can be closed.

**Comment by alexualbu** [comment]
@robertreborm excellent :) i think you can close it yourself
